# Generated by Django 5.0.6 on 2024-09-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_recog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_model',
            name='image',
            field=models.ImageField(null=True, upload_to='model_evaluate_img/'),
        ),
    ]
