# Generated by Django 5.0.6 on 2024-09-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_recog', '0002_alter_about_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_model',
            name='image_of_what',
        ),
        migrations.AddField(
            model_name='about_model',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
